interface UserActionTypesInterface {
  SET_CURRENT_USER: String;
  GOOGLE_SIGN_IN_START: String;
  EMAIL_SIGN_IN_START: String;
  SIGN_IN_SUCCESS: String;
  SIGN_IN_FAILURE: String;
  CHECK_USER_SESSION: String;
  SIGN_OUT_START: String;
  SIGN_OUT_SUCCESS: String;
  SIGN_OUT_FAILURE: String;
  SIGN_UP_START: String;
  SIGN_UP_SUCCESS: String;
  SIGN_UP_FAILURE: String;
  CHECKOUT_SUCCESS: String;
}

const UserActionTypes: UserActionTypesInterface = {
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  GOOGLE_SIGN_IN_START: 'GOOGLE_SIGN_IN_START',
  EMAIL_SIGN_IN_START: 'EMAIL_SIGN_IN_START',
  SIGN_IN_SUCCESS: 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILURE: 'SIGN_IN_FAILURE',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  SIGN_OUT_START: 'SIGN_OUT_START',
  SIGN_OUT_SUCCESS: 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILURE: 'SIGN_OUT_FAILURE',
  SIGN_UP_START: 'SIGN_UP_START',
  SIGN_UP_SUCCESS: 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'SIGN_UP_FAILURE',
  CHECKOUT_SUCCESS: 'CHECKOUT_SUCCESS',
};

export default UserActionTypes;
